# Generated by Django 5.2 on 2026-03-14 23:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_x', models.FloatField(verbose_name='UTM X')),
                ('utm_y', models.FloatField(verbose_name='UTM Y')),
                ('co2_value', models.FloatField(verbose_name='Valor CO2')),
                ('zone_name', models.CharField(max_length=100, verbose_name='Nombre de la zona')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Punto geográfico (lat, lon)', srid=4326, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Medición de CO2',
                'verbose_name_plural': 'Mediciones de CO2',
                'db_table': 'co2_measurements',
                'indexes': [models.Index(fields=['zone_name'], name='co2_measure_zone_na_c9bf8a_idx'), models.Index(fields=['co2_value'], name='co2_measure_co2_val_26553a_idx'), models.Index(fields=['created_at'], name='co2_measure_created_dcd250_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, default='', max_length=200, verbose_name='Institución')),
                ('role', models.CharField(blank=True, default='', max_length=100, verbose_name='Rol / Cargo')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografía')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
